# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
  windows: circleci/windows@2.1.0
jobs:
  build:
    executor:
      name: windows/default
      shell: powershell.exe
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v . -race -coverprofile=coverage.txt -covermode=atomic
      - codecov/upload:
        file: ./coverage.txt
