# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1
orbs:
  windows: circleci/windows@2.1.0
jobs:
  build:
    executor:
      name: windows/default
      shell: powershell.exe
    steps:
      - checkout
      - run: $ProgressPreference = "SilentlyContinue"
      - run: rm -r C:\Go
      - run: (New-Object System.Net.WebClient).DownloadFile("https://dl.google.com/go/go1.14.2.windows-amd64.zip", "go1.14.2.windows-amd64.zip")
      - run: Expand-Archive go1.14.2.windows-amd64.zip
      - run: mv .\go1.14.2.windows-amd64\go C:\
      - run: go get -v -t -d ./...
      - run: go test -v . -race -coverprofile=C:\coverage.txt -covermode=atomic
      - run: (New-Object System.Net.WebClient).DownloadFile("https://github.com/codecov/codecov-exe/releases/download/1.10.0/codecov-windows-x64.exe", "codecov.exe")
      - run: codecov.exe -f C:\coverage.txt -t %CODECOV_TOKEN%
