- FullPath: "C:\\$MFT"
  IsFullPathRegex: false
  FileName: "$MFT"
  IsFileNameRegex: false
- FullPath: "%SYSTEMDRIVE%:\\\\Windows\\\\System32\\\\winevt\\\\Logs\\\\.*\\.evtx$"
  IsFullPathRegex: true
  FileName: ".*\\.evtx$"
  IsFileNameRegex: true
- FullPath: "%SYSTEMDRIVE%:\\Windows\\System32\\config\\SYSTEM"
  IsFullPathRegex: false
  FileName: "SYSTEM"
  IsFileNameRegex: false
- FullPath: "%SYSTEMDRIVE%:\\Windows\\System32\\config\\SOFTWARE"
  IsFullPathRegex: false
  FileName: "SOFTWARE"
  IsFileNameRegex: false
- FullPath: "%SYSTEMDRIVE%:\\\\users\\\\([^\\\\]+)\\\\ntuser.dat"
  IsFullPathRegex: true
  FileName: "ntuser.dat"
  IsFileNameRegex: false
- FullPath: "%SYSTEMDRIVE%:\\\\Users\\\\([^\\\\]+)\\\\AppData\\\\Local\\\\Microsoft\\\\Windows\\\\usrclass.dat"
  IsFullPathRegex: true
  FileName: "usrclass.dat"
  IsFileNameRegex: false
- FullPath: "%SYSTEMDRIVE%:\\\\Users\\\\([^\\\\]+)\\\\AppData\\\\Local\\\\Microsoft\\\\Windows\\\\WebCache\\\\WebCacheV01.dat"
  IsFullPathRegex: true
  FileName: "WebCacheV01.dat"
  IsFileNameRegex: false